config/routes.rb
Phoenix::Application.routes.draw do

 resources :product_types do
    resources :product_cataloges
  end

  resources :leftpop
  resources :rightpop
  resources :privacy
  resources :transactions
  resources :aboutus
  resources :recruit
  resources :faq
  resources :registsuccess
  resources :copyright
  resources :benefit
  resources :voiceservice
  
  match "/bindex" => "transactions#bindex"
  match "/products/find_title" => "products#find_title"
  match "/products/borrow" => "products#borrow"
  match "/products/update_cata_level_2" => "products#update_cata_level_2"
  match "/products/search" => "products#search"
  
  resources :products do
  resources :DataFiles
  end

  resources :customers

  devise_for :users, :controllers => { :registrations => "my_registration" }
  devise_for :users do
  match 'logout' => 'devise/sessions#destroy'
  end

  get "home/index"

  match "/upload" => "upload#index"
  match "/upload/uploadFile" => "upload#uploadFile"
  match "/delete/datafile" => "DataFile#destroy"

   root :to => "home#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/counter.rb
class Counter < ActiveRecord::Base

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :user
  attr_protected :credits
end

app/models/data_file.rb
class DataFile < ActiveRecord::Base

 belongs_to :product

 def self.savefile(filename,user_id, product_id)
    # update to data base
   @datafile = DataFile.new
   @datafile.path=filename
   @datafile.user_id=user_id
   @datafile.product_id=product_id
   @datafile.save  
 end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :impressions, :as=>:impressionable
  has_paper_trail :on => [:update, :destroy]
  belongs_to :user
  has_many :DataFiles, :dependent => :destroy
  has_many :Transactions, :dependent => :destroy
  validates :cata_level_1,  :presence => true
  validates :cata_level_2,  :presence => true
  
  def impression_count
    impressions.size
  end

  def unique_impression_count
    impressions.group(:ip_address).size #UNTESTED: might not be correct syntax
  end

end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
 validates :name,  :presence => true
 has_many :product_cataloges, :dependent => :destroy
 def tname
    I18n.t("#{name.to_s}.#{name.to_s}")
 end
end

app/models/set_default.rb
class SetDefault < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  has_paper_trail :on => [:update, :destroy]
  belongs_to :product
  belongs_to :user
  validates_columns :status
  def self.logtransaction(borrower, product, status,bc,lc)
    @transaction = Transaction.new
    @transaction.product_id = product
    @transaction.user_id  = borrower
    @transaction.trans_stime = Time.now.inspect
    @transaction.status = :borrowing
    @transaction.borrow_customer = bc
    @transaction.lent_customer = lc
    @transaction.save
   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #:token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :products, :dependent => :destroy
  has_many :customers, :dependent => :destroy
end

# migration
class DeviseCreateUsers < ActiveRecord::Migration
  def self.up
    create_table(:users) do |t|
      t.database_authenticatable :null => false
      #t.confirmable
      t.recoverable
      t.rememberable
      t.trackable
      # t.lockable :lock_strategy => :failed_attempts, :unlock_strategy => :both

      t.timestamps
    end

    add_index :users, :email,                :unique => true
    # add_index :users, :confirmation_token,   :unique => true
    add_index :users, :reset_password_token, :unique => true
    # add_index :users, :unlock_token,         :unique => true
  end
  def self.down
    drop_table :users
  end
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  #before_filter :isadmin
  # GET /product_types
  # GET /product_types.xml
  def index
    @product_types = ProductType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @product_types }
    end
  end

  # GET /product_types/1
  # GET /product_types/1.xml
  def show
    @product_type = ProductType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product_type }
    end
  end

  # GET /product_types/new
  # GET /product_types/new.xml
  def new
    @product_type = ProductType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product_type }
    end
  end

  # GET /product_types/1/edit
  def edit
    @product_type = ProductType.find(params[:id])
  end

  # POST /product_types
  # POST /product_types.xml
  def create
    @product_type = ProductType.new(params[:product_type])

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to(@product_type, :notice => 'Product type was successfully created.') }
        format.xml  { render :xml => @product_type, :status => :created, :location => @product_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /product_types/1
  # PUT /product_types/1.xml
  def update
    @product_type = ProductType.find(params[:id])

    respond_to do |format|
      if @product_type.update_attributes(params[:product_type])
        format.html { redirect_to(@product_type, :notice => 'Product type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1
  # DELETE /product_types/1.xml
  def destroy
    @product_type = ProductType.find(params[:id])
    @product_type.destroy

    respond_to do |format|
      format.html { redirect_to(product_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/benefit_helper.rb
module BenefitHelper
end

app/helpers/borrow_helper.rb
module BorrowHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/leftpop_helper.rb
module LeftpopHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/product_types/_form.html.erb
<%= form_for(@product_type) do |f| %>
  <% if @product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

      <ul>
      <% @product_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_types/edit.html.erb
<h1>Editing product_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_type %> |
<%= link_to 'Back', product_types_path %>

app/views/product_types/index.html.erb
<h1>Listing product_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @product_types.each do |product_type| %>
  <tr>
    <td><%= product_type.name %></td>
    <td><%= link_to 'Show', product_type %></td>
    <td><%= link_to 'Edit', edit_product_type_path(product_type) %></td>
    <td><%= link_to 'Destroy', product_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product type', new_product_type_path %>

app/views/product_types/new.html.erb
<h1>New product_type</h1>

<%= render 'form' %>

<%= link_to 'Back', product_types_path %>

app/views/product_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product_type.name %>
</p>

<h2>Cataloges:</h2>
<%= render @product_type.product_cataloges %>

<h2>Add a cataloge:</h2>
<%= form_for([@product_type, @product_type.product_cataloges.build]) do |f| %>
  <div class="field">
    <%= f.label "name" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<br />

<%= link_to 'Edit', edit_product_type_path(@product_type) %> |
<%= link_to 'Back', product_types_path %>