config/routes.rb
Phoenix::Application.routes.draw do

 resources :product_types do
    resources :product_cataloges
  end

  resources :leftpop
  resources :rightpop
  resources :privacy
  resources :transactions
  resources :aboutus
  resources :recruit
  resources :faq
  resources :registsuccess
  resources :copyright
  resources :benefit
  resources :voiceservice
  
  match "/bindex" => "transactions#bindex"
  match "/products/find_title" => "products#find_title"
  match "/products/borrow" => "products#borrow"
  match "/products/update_cata_level_2" => "products#update_cata_level_2"
  match "/products/search" => "products#search"
  
  resources :products do
  resources :DataFiles
  end

  resources :customers

  devise_for :users, :controllers => { :registrations => "my_registration" }
  devise_for :users do
  match 'logout' => 'devise/sessions#destroy'
  end

  get "home/index"

  match "/upload" => "upload#index"
  match "/upload/uploadFile" => "upload#uploadFile"
  match "/delete/datafile" => "DataFile#destroy"

   root :to => "home#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/counter.rb
class Counter < ActiveRecord::Base

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :user
  attr_protected :credits
end

app/models/data_file.rb
class DataFile < ActiveRecord::Base

 belongs_to :product

 def self.savefile(filename,user_id, product_id)
    # update to data base
   @datafile = DataFile.new
   @datafile.path=filename
   @datafile.user_id=user_id
   @datafile.product_id=product_id
   @datafile.save  
 end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :impressions, :as=>:impressionable
  has_paper_trail :on => [:update, :destroy]
  belongs_to :user
  has_many :DataFiles, :dependent => :destroy
  has_many :Transactions, :dependent => :destroy
  validates :cata_level_1,  :presence => true
  validates :cata_level_2,  :presence => true
  
  def impression_count
    impressions.size
  end

  def unique_impression_count
    impressions.group(:ip_address).size #UNTESTED: might not be correct syntax
  end

end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
 validates :name,  :presence => true
 has_many :product_cataloges, :dependent => :destroy
 def tname
    I18n.t("#{name.to_s}.#{name.to_s}")
 end
end

app/models/set_default.rb
class SetDefault < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  has_paper_trail :on => [:update, :destroy]
  belongs_to :product
  belongs_to :user
  validates_columns :status
  def self.logtransaction(borrower, product, status,bc,lc)
    @transaction = Transaction.new
    @transaction.product_id = product
    @transaction.user_id  = borrower
    @transaction.trans_stime = Time.now.inspect
    @transaction.status = :borrowing
    @transaction.borrow_customer = bc
    @transaction.lent_customer = lc
    @transaction.save
   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #:token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :products, :dependent => :destroy
  has_many :customers, :dependent => :destroy
end

# migration
class DeviseCreateUsers < ActiveRecord::Migration
  def self.up
    create_table(:users) do |t|
      t.database_authenticatable :null => false
      #t.confirmable
      t.recoverable
      t.rememberable
      t.trackable
      # t.lockable :lock_strategy => :failed_attempts, :unlock_strategy => :both

      t.timestamps
    end

    add_index :users, :email,                :unique => true
    # add_index :users, :confirmation_token,   :unique => true
    add_index :users, :reset_password_token, :unique => true
    # add_index :users, :unlock_token,         :unique => true
  end
  def self.down
    drop_table :users
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #impressionist :actions=>[:index] 
  def index
    #@products = Product.all(:order => "RAND()", :limit => 5)
    #@products = Product.where("cata_level_1 = :type", :type => 1).all(:order => "RAND()", :limit => 10)
    @product_types = ProductType.all 
    @home_page = 1
    @products_div = [] 
    @product_types.each do |pd|
    @products_div[pd.id]  = Product.where("cata_level_1 = :type", :type => pd.id ).all(:order => "RAND()", :limit => 0)
    end
    @producs_prompt = Product.where("prompt = :pr", :pr => true).all(:order => "RAND()", :limit => 30)
    #only keep code here
    #current_user.update_attribute :admin, true
    #logger.debug "debugging" + @@cnt.to_s
    @icnt = 1688
    @counter = Counter.all
    if @counter.length == 0 
	@counter = Counter.new
	@counter.number = 1688
	@counter.save
    else
	@icnt = @counter.first.number
    end
    #logger.debug "debuggingg" + session[:stay]
    if session[:stay].nil?
	@counter.first.number += 1
	@counter.first.save
    end
    session[:stay] = request.session_options[:id]
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/benefit_helper.rb
module BenefitHelper
end

app/helpers/borrow_helper.rb
module BorrowHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/leftpop_helper.rb
module LeftpopHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/recruit_helper.rb
module RecruitHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<style>
.user_new {float: right;
width:300px;
margin:auto;
margin-top: 20px;
margin-right: 15px;
color: blue;
}
#user_new fieldset{
adding:1px;
}
#user_new legend{
	font-weight:bold;
	font-size:12pt;
}

#user_new label{
	height:20px;
	background-color:transparent;
	color: black;
	padding-top: 1px;
	padding-right: 1px;
	padding-bottom: 0;
	padding-left: 2px;
	width: auto;
}
#user_new input {
margin-right:8px;
border:1px solid #999999;
float:right;
clear:right;
background:#CCCCCC;
}
#user_new input:focus,#user_new input:hover {
border:1px solid #333333;
}
</style>

<div id="wrapper">
  <div id="header">
  <!---%= link_to image_tag("logo.jpg", :class => "logo"), root_path %-->
  <% if ! user_signed_in?   %>
  <%= render :template => 'devise/sessions/new' %>
  <% end  %>
  </div>
  <div id="nav">
    <div id="navPyra">
     <ul>
        <li>
        <%= link_to t(:aboutus), aboutus_path  %>
        </li>
        <li>
        <%= link_to t(:browse_products), products_path  %>
        </li>
        <li>
        <%= link_to t(:benefit), benefit_index_path  %>
        </li>
        <li>
        <%= link_to t(:voiceservice), voiceservice_index_path  %>
        </li>
        <li>
        <%= link_to t(:my_transactions), transactions_path  %>
        </li>
        <li>
        <%= link_to t(:share_my_goods), new_product_path  %>
        </li>
       <li>
      <div id="topBar"> 
       <%= form_tag '/products/find_title', :method => 'get' do %>
           <%= text_field 'title','name' , :size => 15 %>
           <%= submit_tag t(:search) %>
         <% end  %> 
      </div>
       </li>
      </ul>
    </div>
  </div>
    <script type="text/javascript">
        $(function() {
            $('#menu1').menuTree({
                expandSpeed: 1000,
                collapseSpeed: 1000,
                parentMenuTriggerCallback: false,
                multiOpenedSubMenu: true});
        });
</script>
  <div id="bodyleft">
    <div class="body_p">
      <div id="menu1" class="menuTree">
        <% for @pt in  @product_types %> 
	 <ul> 
	  <li class="parent expanded"><a href="#" mce_href=""><%= @pt.tname %></a>
	   <ul>
           <% for @pc in @pt.product_cataloges %>
	    <li class="child"><%= link_to @pc.tname, products_search_path(:pt => @pt.id, :pc => @pc.id) %>
	   <% end %>
           </ul> 
          </li> 
	 </ul> 
        <% end %>
      </div>
    </div>
  </div> 
  <div id="bodycenter">
      <%= render :template => 'products/index' %>
  </div>
  <div id="bodyright">
  <p class="ack"><%= t('acknowledge.ack')  %>  </p>
  <marquee scrollamount="2" direction="up" >
  <p><%= t('acknowledge.cjg')  %></p>   
  <p><%= t('acknowledge.xrt')  %></p>   
  <p><%= t('acknowledge.zqx')  %></p>   
  <p><%= t('acknowledge.cyq')  %></p>   
  <p><%= t('acknowledge.wwl')  %></p>   
  <p><%= t('acknowledge.lwr')  %></p>   
  <p><%= t('acknowledge.wzj')  %></p>   
  <p><%= t('acknowledge.google')  %></p>   
  <p><%= t('acknowledge.delta')  %></p>   
  <p><%= t('acknowledge.yzu')  %></p>   
  <p>Money</p>   
  <p>Robin</p>   
  <p>Hake</p>   
  <p>May Be you are the next</p> 
  </marquee>
  <%= render :template => 'rightpop/index' %>
  <%= render :template => 'leftpop/index' %>
  </div>
  <div id="footer">
    <div class="footer_p">
      <%= link_to image_tag("facebook_24.png"), root_path %>
     <%= link_to image_tag("rss_24.png"), root_path %>
      <a href="http://www.enjoybee.com/">Copyright 2011-2012 包租蜂網路科技 ALL RIGHTS RESERVED.</a>
      <div class="footer_textL">
        <%= link_to t(:recruit), recruit_index_path %>
        <%= mail_to "happy@enjoybee.com", t(:blog) %>
        <%= link_to t(:privacy), privacy_index_path %>
        <%= link_to t(:copyright), copyright_index_path %>
        <%= link_to t(:faq), faq_index_path %>
	<%= @icnt %>
      </div>
    </div>
  </div>
<!--- div class="facebook">
<iframe src="http://www.facebook.com/widgets/like.php?href=http://www.enjoybee.com" scrolling="no" frameborder="0" style="border:none; width:450px; height:80px"></iframe>   
</div>
-->
</div>

app/views/home/index_bk.html.erb
<html>    
    <head>        
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />        
        <style type="text/css">
	html,body{height:100%; margin:5; padding:5;}
	.logo{float:left;height:80px; width:auto}
	img.normal{height:auto; width:auto}
	#layout_products{float:left; background:#FFFFFF; width:auto; height:auto; margin:4px;}
	#layout_foot{float:right; background:#FFFFFF; width:85%; height::auto; margin:2px;}
	#layout_25{background:#FFFFFF; width:auto;margin:5px;border:solid 5px white;}
	.floatstop{clear:both;}
        #layout_right{float:right; background:#00FFFF;text-align:left}
        #products{float:left; margin:10px;margin:10px;display:inline;}
        .layout_top li{ float:left; margin:10px;font:12px;display:inline;}
        .layout_top li a {display:block; padding:8px 50px;background:#3A4953;color:#fff; text-decoration:none;border-right:1px solid #000;text-align:center}
        .layout_top li a:hover {background:#146C9C;color:#fff;text-decoration:none;border-right:1px solid #000;}
        #search {
              position:relative;
	      left: 30%;
	      background: #FFFFFF;
	      padding:2px;
	      font-family:arial;
              width:100%;
	}
        #layout_menu {float:left;}
	</style>
    <script type="text/javascript">
        $(function() {
            $('#menu1').menuTree();

            $('#menu2').menuTree({
                expandSpeed: 1000,
                collapseSpeed: 1000,
                expandEasing: 'easeOutBounce',
                collapseEasing: 'easeOutBounce',
                parentMenuTriggerCallback: false,
                multiOpenedSubMenu: true
            });
            $('#menu3').menuTree({
                expandedNode: '2.1'
            }, function(rel) {
                alert(rel);
            });
        });
    </script>
</head>    
    <body> 
        <div>
        <%= link_to image_tag("logo.jpg", :class => "logo"), root_path %>
        <ul class="layout_top">
	<li>
        <%= link_to t(:browse_products), products_path  %>
         </li>
       <% if user_signed_in? %>
	<li>
        <%= link_to t(:share_my_goods), new_product_path  %>
         </li>
	<li>
        <%= link_to t(:my_transactions), transactions_path  %>
         </li>
       <% end  %>
         <li>
        <%= link_to t(:register), new_user_registration_path %>
         </li>
         <li>
        <%= link_to t(:login), user_session_path %>
         </li>
	<li>
        <%= mail_to "happy@enjoybee.com", t(:blog) %>
         </li>
         <li>
        <%= link_to t(:aboutus), aboutus_path  %>
         </li>
         <li>
        <%= link_to t(:recruit), recruit_index_path %>
<!---a id="setHomePage" style="behavior:url(#default#homepage);" onclick="SetHome(this)" href="javascript:void(0);"><%= t(:topme) %></a--->       
         </li>
         <li>
        <%= link_to t(:faq), faq_index_path %>
         </li>
        </ul>
        </div>
        <p class="floatstop"></p>
	<div id="search">            
                <!-- form name="serc" method="get" action="http://www.google.com">                    
                    <input name="searchfrom" value="headbar" type="hidden">                    
                    <input name="k" onKeyDown="if(event.keyCode == 13) document.serc.submit();" width=10 type="text">                    
                    < %= submit_tag "google search" % >                
                </form-->
               <%= form_tag '/products/find_title', :method => 'get' do %>
                 <%= text_field 'title','name' , :size => 20 %>
                 <%= submit_tag t(:search) %>
                <% end  %> 
        </div> 
        <div id="layout_menu"> 
	<div id="menu1" class="menuTree">
        <% for @pt in  @product_types %> 
	 <ul> 
	  <li class="parent"><a href="#" mce_href=""><%= @pt.tname %></a>
	   <ul>
           <% for @pc in @pt.product_cataloges %>
	    <li class="child"><%= link_to @pc.tname, products_search_path(:pt => @pt.id, :pc => @pc.id) %>
	   <% end %>
           </ul> 
          </li> 
	 </ul> 
        <% end %>
        </div>
        <p class="floatstop"></p>
        </div>
	<div id="layout_products">        
         <p>
	<%= render :template => 'products/index' %>
         </p>
        </div>
        <p class="floatstop"></p>
   </body>
    </html>