config/routes.rb
Phoenix::Application.routes.draw do

 resources :product_types do
    resources :product_cataloges
  end

  resources :leftpop
  resources :rightpop
  resources :privacy
  resources :transactions
  resources :aboutus
  resources :recruit
  resources :faq
  resources :registsuccess
  resources :copyright
  resources :benefit
  resources :voiceservice
  
  match "/bindex" => "transactions#bindex"
  match "/products/find_title" => "products#find_title"
  match "/products/borrow" => "products#borrow"
  match "/products/update_cata_level_2" => "products#update_cata_level_2"
  match "/products/search" => "products#search"
  
  resources :products do
  resources :DataFiles
  end

  resources :customers

  devise_for :users, :controllers => { :registrations => "my_registration" }
  devise_for :users do
  match 'logout' => 'devise/sessions#destroy'
  end

  get "home/index"

  match "/upload" => "upload#index"
  match "/upload/uploadFile" => "upload#uploadFile"
  match "/delete/datafile" => "DataFile#destroy"

   root :to => "home#index"

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :authenticate_user!
  # GET /transactions
  # GET /transactions.xml
  def index
    #@transactions = Transaction.all.paginate(:page => params[:page])
    #order(:updated_at)
    @transactions = Transaction.joins(:product => :user).where("users.id = :id", :id => current_user.id).paginate(:page => params[:page])
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transactions }
    end
  end
  
  def bindex
    #@transactions = Transaction.all.paginate(:page => params[:page])
    #order(:updated_at)
    @transactions = Transaction.where("user_id = :id", :id => current_user.id).order(:updated_at).paginate(:page => params[:page])
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.xml
  def show
    @transaction = Transaction.find(params[:id])
    @borrow_mail = User.find_by_id(@transaction.user_id).email
    if ! @transaction.borrow_customer.nil?
    @bc = Customer.find_by_id(@transaction.borrow_customer) 
    end
    if ! @transaction.lent_customer.nil?
    @lc = Customer.find_by_id(@transaction.lent_customer) 
    end
    if ! @transaction.product_id.nil?
    @pd = Product.find_by_id(@transaction.product_id) 
    end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.xml
  def new
    if params[:product_id].nil?
       redirect_to products_path,:notice => 'Can not access this directly'
    else
    	@transaction = Transaction.new
    	respond_to do |format|
      		format.html # new.html.erb
      		format.xml  { render :xml => @transaction }
    	end
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
    @pd = Product.find(@transaction.product_id) 
    if (current_user.id != @transaction.product.user.id ) \
	and (current_user.id != @transaction.user.id )
       redirect_to products_path,:notice => t(:noauth)
    else
       @lc = User.find_by_id(@transaction.product.user.id).customers
       @bc = User.find_by_id(@transaction.user.id).customers
    end
  end

  # POST /transactions
  # POST /transactions.xml
  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully created.') }
        format.xml  { render :xml => @transaction, :status => :created, :location => @transaction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.xml
  def update
    @transaction = Transaction.find(params[:id])
    @pd = Product.find(@transaction.product_id) 
    if (current_user.id != @transaction.product.user.id ) \
	and (current_user.id != @transaction.user.id )
       redirect_to products_path,:notice => t(:noauth)
    else
       @lc = User.find_by_id(@transaction.product.user.id).customers
       @bc = User.find_by_id(@transaction.user.id).customers
       Notifier.update(current_user,@pd).deliver
       Notifier.update( @transaction.product.user, @pd).deliver
    end
        
    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to(@transaction, :notice => t(:successupdatetrans)) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.xml
  def destroy
    @transaction = Transaction.find(params[:id])
    @cid =  @transaction.user_id
    @transaction.destroy
    if @cid == current_user.id
    	respond_to do |format|
      		format.html { redirect_to(bindex_url) }
      		format.xml  { head :ok }
    	end
    else
    	respond_to do |format|
      		format.html { redirect_to(transactions_url) }
      		format.xml  { head :ok }
    	end
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :trans_stime %><br />
    <%= f.date_select :trans_stime %>
  </div>
  <div class="field">
    <%= f.label :trans_etime %><br />
    <%= f.text_field :trans_etime %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :borrow_customer %><br />
    <%= f.text_field :borrow_customer %>
  </div>
  <div class="field">
    <%= f.label :lent_customer %><br />
    <%= f.text_field :lent_customer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/_update.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% if ! @pd.nil?  %>
  <div class="field">
    <%= f.label t(:name) %><br />
    <%= @pd.name %>
  </div>
<% end %>
  <div class="field">
    <%= f.label t(:transtime) %><br />
    <%= f.date_select :trans_stime, :disabled => 'disabled'%>
  </div>
  <div class="field">
    <%= f.label t(:tranetime) %><br />
    <%= f.text_field :trans_etime, :disabled => 'disabled'%>
  </div>
  <div class="field">
    <%= f.label t(:status) %><br />
    <%= f.select :status,[ [t(:borrowing),:borrowing], [t(:confirming), :confirming], [t(:lenting), :lenting], [t(:logistic),:logistic] ] %>
  </div>
<% if ! @bc.nil?  %>
  <div class="field">
    <%= f.label t(:borrower) %><br />
    <% for @b in @bc  %>
    <%= f.radio_button :borrow_customer, @b.id %><%= @b.nickname %><br />
    <%= @b.phone  %>
    <% end %>
  </div>
<% end  %>

<% if ! @lc.nil?  %>
  <div class="field">
    <%= f.label t(:lender) %><br />
    <% for @l in @lc  %>
    <%= f.radio_button :lent_customer, @l.id %><%= @l.nickname %><br />
    <% end  %>
  </div>
<% end  %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/bindex.html.erb
<h1><%= link_to t(:listtrans), transactions_path %></h1>

<table>
  <tr>
    <th><%= t(:name)%></th>
    <th><%= t(:transtime) %></th>
    <th><%= t(:tranetime) %></th>
    <th><%= t(:status) %></th>
    <th><%= t(:borrower) %></th>
    <th><%= t(:lender) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= will_paginate_with_i18n @transactions%>
<% @transactions.each do |transaction| %>
    <td>
      <% @pd = Product.find_by_id(transaction.product_id)  %>
      <% if @pd %>
        <%= link_to @pd.name, product_path(@pd)%>
      <% end %>
    </td>
    <td><%= transaction.trans_stime %></td>
    <td><%= transaction.trans_etime %></td>
    <td><%= t(transaction.status) %></td>
    <td>
       <% if transaction.borrow_customer.nil? %>
        <% else %>
           <% if (@bc = Customer.find_by_id(transaction.borrow_customer))  %>
              <%=link_to @bc.nickname, customer_path(@bc) %>
           <% end  %>
        <% end  %>
    </td>
    <td>
       <% if transaction.lent_customer.nil? %>

       <% else %>
          <% if ( @lc = Customer.find_by_id(transaction.lent_customer))  %>
            <%=link_to @lc.nickname, customer_path(@lc) %>
         <% end  %>
       <% end  %>
    </td>
    <td><%= link_to t(:show), transaction %></td>
    <td><%= link_to t(:edit), edit_transaction_path(transaction) %></td>
     <% if (current_user.email.to_s.match("hakehuang"))  %>
    <td><%= link_to t(:destory), transaction, :confirm => t(:ays), :method => :delete %></td>
     <% end  %>
  </tr>
<% end %>
</table>

<br />

<%= will_paginate_with_i18n @transactions%>
<!-- %= link_to 'New Transaction', new_transaction_path %--->

app/views/transactions/edit.html.erb
<h1><%= t(:edit)  %></h1>

<%= render 'update' %>

<%= link_to t(:show), @transaction %> |
<%= link_to t(:back), transactions_path %>

app/views/transactions/index.html.erb
<h1><%= link_to t(:listtrans), bindex_path %></h1>

<table>
  <tr>
    <th><%= t(:name)%></th>
    <th><%= t(:transtime) %></th>
    <th><%= t(:tranetime) %></th>
    <th><%= t(:status) %></th>
    <th><%= t(:borrower) %></th>
    <th><%= t(:lender) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= will_paginate_with_i18n @transactions%>
<% @transactions.each do |transaction| %>
    <td>
      <% @pd = Product.find_by_id(transaction.product_id)  %>
      <% if @pd %>
        <%= link_to @pd.name, product_path(@pd)%>
      <% end %>
    </td>
    <td><%= transaction.trans_stime %></td>
    <td><%= transaction.trans_etime %></td>
    <td><%= t(transaction.status) %></td>
    <td>
       <% if transaction.borrow_customer.nil? %>
        <% else %>
           <% if (@bc = Customer.find_by_id(transaction.borrow_customer))  %>
              <%=link_to @bc.nickname, customer_path(@bc) %>
           <% end  %>
        <% end  %>
    </td>
    <td>
       <% if transaction.lent_customer.nil? %>

       <% else %>
          <% if ( @lc = Customer.find_by_id(transaction.lent_customer))  %>
            <%=link_to @lc.nickname, customer_path(@lc) %>
         <% end  %>
       <% end  %>
    </td>
    <td><%= link_to t(:show), transaction %></td>
    <td><%= link_to t(:edit), edit_transaction_path(transaction) %></td>
     <% if (current_user.email.to_s.match("hakehuang"))  %>
    <td><%= link_to t(:destory), transaction, :confirm => t(:ays), :method => :delete %></td>
     <% end  %>
  </tr>
<% end %>
</table>

<br />

<%= will_paginate_with_i18n @transactions%>
<!-- %= link_to 'New Transaction', new_transaction_path %--->

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<% if ! @pd.nil?  %>
<p>
  <b><%= t(:name) %></b>
  <%= link_to @pd.name  ,product_path(@transaction.product_id) %>
</p>
<% end %>
<p>
  <b><%= t(:transtime)  %></b>
  <%= @transaction.trans_stime %>
</p>

<p>
  <b><%= t(:tranetime)  %></b>
  <%= @transaction.trans_etime %>
</p>

<p>
  <b><%= t(:status)  %></b>
  <%= t(@transaction.status) %>
</p>

<p>
  <b><%= t(:borrower)  %></b>
   <b><%= @borrow_mail %></b>
<% if ! @bc.nil?  %>
  <%= link_to @bc.nickname,customer_path(@bc)  %>
<% end %>
</p>

<% if ! @lc.nil?  %>
<p>
  <b><%= t(:lender)  %></b>
  <%=link_to  @lc.nickname, customer_path(@lc) %>
</p>

<% end %>

<%= link_to t(:edit), edit_transaction_path(@transaction) %> |
<%= link_to t(:back), transactions_path %>